@api = http://localhost:5000/anotaciones

POST  {{api}}/
Content-Type: application/json

{
    "idUsuario": "60c96e20d58cca1298b4d656",
    "idLibro": "60dbb1278b62f60f880bd518",
    "ultimaPagina": 45,
    "pagina": 44,
    "fecha":"2012/12/12",
    "descripcion": "Este libro esta buenisimo"
} 
###
GET {{api}}/60c96e20d58cca1298b4d656
 
### Marca el libro la primera vez que lo abre 
PUT {{api}}
Content-Type: application/json

{
    "idUsuario": "60dcd376b93dff27d167380e",
    "idLibro": "60dbb1388b62f60f880bd522"
} 

### Elimina el libro
PUT  {{api}}/delete/ANOTACION005
Content-Type: application/json

{
    "idUsuario": "60dcd376b93dff27d167380e",
    "idLibro": "60dbb1388b62f60f880bd522"
} 